version: "3"
services:
    backend:
        image: sudoku-backend:latest
        build:
            context: backend
        ports:
            - "8001:80"
        environment:
            ASPNETCORE_ENVIRONMENT: "Production"

    frontend:
        image: sudoku-frontend:latest
        build:
            context: frontend
        ports:
            - "8000:80"